### ISSUE TITLE
Hackage release?

### ISSUE THREAD

**Issue by fractalcat** [anchor/roundtrip-aeson#18]
This package is handy; releasing it on Hackage would make it moreso.

**Comment by thsutton** [comment]
I shall do so this morning.

**Comment by fractalcat** [comment]
\o/ Much appreciated.

**Comment by thsutton** [comment]
Stacked, Travised, waiting for a green and then I'll upload it.

**Comment by thsutton** [comment]
Done. https://hackage.haskell.org/package/roundtrip-aeson
